<script setup>
import { computed } from 'vue'
import { useData } from 'vitepress'
import { findCourse } from '../course-catalog.mjs'
import { lecturePath, lectureSlides, readingMinutes } from '../lecture-model.mjs'
import { studyLink } from './links'
const { frontmatter } = useData()
const course = computed(() => findCourse(frontmatter.value.course))
const groups = computed(() => course.value.parts?.length ? course.value.parts.map(p => ({ ...p, entries: p.lessons.map(slug => course.value.lessons.find(l => l.slug === slug)).filter(Boolean) })) : [{ title: 'Bài giảng', entries: course.value.lessons }])
</script>
<template><main v-if="course" class="course-overview course-shell"><nav class="book-breadcrumbs" aria-label="Đường dẫn"><a :href="studyLink('/')">Trang chủ</a><span>/</span><span>Học phần</span></nav><h1>{{ course.name }}</h1><p class="course-description">{{ course.description }}</p><div class="course-meta"><span>{{ course.lessons.length }} bài giảng</span><span>{{ course.foundations.length }} khái niệm nền</span><a :href="studyLink(`/${course.id}/bai-tap`)">Bài tập ôn luyện</a><a :href="studyLink(`/${course.id}/notes/lo-trinh`)">Lộ trình và tài liệu</a></div><section v-for="group in groups" :key="group.title" class="course-part-section"><header class="part-banner"><h2>{{ group.title }}</h2><p v-if="group.description" class="part-description">{{ group.description }}</p></header><div class="lecture-list"><article v-for="lesson in group.entries" :key="lesson.slug"><a class="lecture-row" :href="studyLink(lecturePath(course.id, lesson.slug))"><span class="lesson-number">{{ lesson.number ?? course.lessons.indexOf(lesson) + 1 }}</span><div class="lecture-list-copy"><h3>{{ lesson.title }}</h3><p>{{ lectureSlides(course, lesson).length }} slide · {{ lesson.prerequisites.length }} khái niệm nền<span v-if="lesson.status === 'ready'"> · khoảng {{ readingMinutes(course.id, lesson.slug) }} phút đọc</span></p></div><span v-if="lesson.status !== 'ready'" class="lesson-status">Bản nháp</span></a></article></div></section><p class="course-wiki-footnote">Trong Notes, bấm vào thuật ngữ có gạch chấm để xem ghi chú nhanh. Khi cần học kỹ hơn, mở <a :href="studyLink('/wiki/')">Wiki thuật ngữ</a>.</p></main></template>
